---
title: "LMA"
author: "W"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
---

```{r echo = FALSE}
# Course: BUAN 5210
# Title: LMA Assignment
# Purpose: Analyze the the relation between individule earnings with his/her educational attainment and the relation between higher education and race/ethnicity
# Date: January 29, 2019
# Author: Ziyu Jin
```

```{r echo = FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 
# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)
```

Prepare the data
=========================================
Work with Washington State data

```{r}
### Load data
wa_data <- read.csv('ss16pwa.csv')
### Subset and focus on the data of interest
# SERIALNO: Housing unit/GQ person serial number  
# SPORDER: Person number
# SEX: Sex                                        
# CIT: Citizenip status
# PERNP: Total person's earnings                  
# SCHL: Educational attainment
# RAC1P: Recoded detailed race code               
# ESR: Employment status
research_data <- wa_data[c('SERIALNO','SPORDER','SEX', 'CIT','PERNP','SCHL','RAC1P','ESR')]
summary(research_data)
```


```{r}
### Data cleaning
## exclude all missing values
new <- na.exclude(research_data) 
## exclude those who cannot work due to age under 16 years old or not in labor force.
new <- new[new['ESR'] != 6, ]
## group educational attainment levels into 5 levels: 
# A: no high school degree; B: with high school degree; 
# C: with colleage degree; D: with professional degree;
# E: with master degree; F: with Doctor degree
for (rows in 1:nrow(new)) {
  if (new[rows, 'SCHL'] <= 19) {
    new[rows, 'EducLevel'] = 'B'
  }
  if (new[rows, 'SCHL'] >= 20 & new[rows, 'SCHL'] <= 21) {
    new[rows, 'EducLevel'] = 'C'
  }
  if (new[rows, 'SCHL'] == 23) {
    new[rows, 'EducLevel'] = 'D'    
  }
  if (new[rows, 'SCHL'] == 22) {
    new[rows, 'EducLevel'] = 'E'
  }
  if (new[rows, 'SCHL'] == 24) {
    new[rows, 'EducLevel'] = 'F'
  }
}
```

```{r}
### Redefine variable citizenship
# 1: US Citizen
# 2: Not US Citizen
for (rows in 1:nrow(new)) {
  if (new[rows, 'CIT'] != 5) {
    new[rows, 'CIT'] = 1
  }
  if (new[rows, 'CIT'] == 5) {
    new[rows, 'CIT'] = 2
  }
}

#Columns name change
new <- new[c("SERIALNO", "SPORDER","SEX", "CIT", "PERNP", "RAC1P", "EducLevel")]
colnames(new) <- c("Housing_Unit","Person_Number", "Sex", "Citizenship", "Total_Person_Earning", "Race", "EducLevel")
new$Citizenship <- as.factor(new$Citizenship)
new$Sex <- as.factor(new$Sex)
new$Race <- as.factor(new$Race)
new$EducLevel <- as.factor(new$EducLevel)
summary(new)
```

```{r}
mod <- lm(Total_Person_Earning ~ EducLevel + Sex + Citizenship + Race, data = new)
summary(mod)
```

